apiVersion: apps/v1
kind: Deployment
metadata:
  name: svs-app-catalog
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.catalog.replicas }}
  selector:
    matchLabels:
      app: svs-app-catalog
  template:
    metadata:
      labels:
        app: svs-app-catalog
      {{- if .Values.catalog.vault.enabled }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ .Values.catalog.vault.role | quote }}
        vault.hashicorp.com/agent-inject-secret-db-creds: {{ .Values.catalog.vault.secretPath | quote }}
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{`{{- with secret "`}}{{ .Values.catalog.vault.secretPath }}{{`" -}}`}}
          DB_USERNAME={{`{{ .Data.data.username }}`}}
          DB_PASSWORD={{`{{ .Data.data.password }}`}}
          {{`{{- end }}`}}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccounts.catalog }}
      containers:
        - name: svs-app
          image: {{ .Values.registry }}/{{ .Values.catalog.image.repository }}:{{ .Values.catalog.image.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.catalog.service.targetPort }}
          resources:
            {{- toYaml .Values.catalog.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: catalog-config
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.catalog.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.catalog.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3