{{- if .Values.customer.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.customers }}
  namespace: {{ .Values.namespace }}
{{- end }}

{{- if .Values.catalog.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.catalog }}
  namespace: {{ .Values.namespace }}
{{- end }}

{{- if .Values.appointment.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.appointments }}
  namespace: {{ .Values.namespace }}
{{- end }}