apiVersion: v1
kind: Secret
metadata:
  name: customer-db-secret
  namespace: svs-microservices
type: Opaque
data:
  CUSTOMER_DB_USER: Y3VzdG9tZXJzX3VzZXI= # "customers_user"
  CUSTOMER_DB_PASS: Q3VzdG9tZXJzUEBzcw== # "CustomersP@ss"