{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  FLASK_SECRET_KEY: {{ .Values.frontend.secrets.flaskSecretKey | b64enc | quote }}
{{- end }}

{{- if and .Values.customer.enabled (not ( .Values.customer.vault | default dict ).enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  CUSTOMER_DB_USER: {{ .Values.customer.secrets.dbUser | b64enc | quote }}
  CUSTOMER_DB_PASS: {{ .Values.customer.secrets.dbPass | b64enc | quote }}
{{- end }}

{{- if and .Values.catalog.enabled (not ( .Values.catalog.vault | default dict ).enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  CATALOG_DB_USER: {{ .Values.catalog.secrets.dbUser | b64enc | quote }}
  CATALOG_DB_PASS: {{ .Values.catalog.secrets.dbPass | b64enc | quote }}
{{- end }}

{{- if and .Values.appointment.enabled (not ( .Values.appointment.vault | default dict ).enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: appointment-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  APPOINTMENT_DB_USER: {{ .Values.appointment.secrets.dbUser | b64enc | quote }}
  APPOINTMENT_DB_PASS: {{ .Values.appointment.secrets.dbPass | b64enc | quote }}
{{- end }}