apiVersion: apps/v1
kind: Deployment
metadata:
  name: svs-app-appointment
  namespace: svs-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svs-app-appointment
  template:
    metadata:
      labels:
        app: svs-app-appointment
    spec:
      containers:
        - name: svs-app
          image: 192.168.56.85:5000/appointments
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: appointment-db-secret
            - configMapRef:
                name: appointment-config