apiVersion: apps/v1
kind: Deployment
metadata:
  name: svs-app-customer
  namespace: svs-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svs-app-customer
  template:
    metadata:
      labels:
        app: svs-app-customer
      # annotations:
      #   vault.hashicorp.com/agent-inject: "true"
      #   vault.hashicorp.com/role: "svs-role"
      #   vault.hashicorp.com/agent-inject-secret-db-creds: "secret/data/svs/db"
      #   vault.hashicorp.com/agent-inject-template-db-creds: |
      #     {{- with secret "secret/data/svs/db" -}}
      #     DB_USERNAME={{ .Data.data.username }}
      #     DB_PASSWORD={{ .Data.data.password }}
      #     {{- end }}        
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "svs-role"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/svs-customer-role"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/svs-customer-role" -}}
          DB_USERNAME={{ .Data.username }}
          DB_PASSWORD={{ .Data.password }}
          {{- end }}
        vault.hashicorp.com/agent-inject-command-db-config: "kill -HUP 1"                 
    spec:
      serviceAccountName: svs-app-sa
      containers:
        - name: svs-app
          image: 192.168.56.85:5000/customer_vault_test
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            # - secretRef:
            #     name: customer-db-secret
            - configMapRef:
                name: customer-config
          # command:
          #   - /bin/sh
          #   - -c
          #   - |
          #     until [ -f /vault/secrets/db-creds ]; do
          #       echo "Waiting for Vault secrets..."
          #       sleep 2
          #     done
          #     exec python app.py                              