name: Build and Deploy to Vagrant K8s

on:
  push:
    branches: [ "main" ]  # Trigger on every push to main

jobs:
  build-and-push-test:
    runs-on: self-hosted  # <--- Targets your Vagrant container
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        # Using the Devbox IP for the registry tag
        run: |
          docker build -t \
          192.168.56.85:5000/frontend-service:${{ github.sha }} \
          -f app-services/frontend_service/Dockerfile .
          docker tag 192.168.56.85:5000/frontend-service:${{ github.sha }} 192.168.56.85:5000/frontend-service:latest

      - name: Push to Local Registry
        run: |
          docker push 192.168.56.85:5000/frontend-service:${{ github.sha }}
          docker push 192.168.56.85:5000/frontend-service:latest

  deploy-to-k8s:
    needs: build-and-push-test
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Update Deployment Image
      #   # This replaces the image tag in your YAML with the specific Git SHA
      #   run: |
      #     sed -i 's|image: .*|image: localhost:5000/frontend-service:${{ github.sha }}|g' k8s/deployments/frontend-deployment.yaml
      - name: Update Deployment Image
        run: |
          echo "--- BEFORE SED ---"
          grep "image:" k8s/deployments/frontend-deployment.yaml
          
          sed -i "s|image:.*|image: 192.168.56.85:5000/frontend-service:${{ github.sha }}|g" k8s/deployments/frontend-deployment.yaml
          
          echo "--- AFTER SED ---"
          grep "image:" k8s/deployments/frontend-deployment.yaml
      - name: Deploy to Cluster
        run: |
          kubectl apply -f k8s/deployments/frontend-deployment.yaml --validate=false
          kubectl rollout status deployment/svs-app-frontend -n svs-microservices